### ISSUE TITLE
Query parameter minimum/maximum validation not generated.

### ISSUE THREAD

**Issue by nmcb** [zalando/play-swagger#38]
A query parameter of type integer with minimum/maximum constraints added is not generated unless the parameter is also required. E.g. The first testcase does not generate for the ```[2000..2100]``` range, while the second one does. This leads to the code generated for the first test case accepting integers outside the minimum/maximum range, for example the parameter ```/?year=3000```.

```yaml
paths:
  /:
    get:
      parameters:
        - name: year
          in: query
          type: integer
          minimum: 2000
          maximum: 2100
```

```yaml
paths:
  /:
    get:
      parameters:
        - name: year
          in: query
          type: integer
          required: true
          minimum: 2000
          maximum: 2100
```
