### ISSUE TITLE
Add support for arrays as path parameters

### ISSUE THREAD

**Issue by slavaschmidt** [zalando/play-swagger#42]
Currently, it is not possible to define a path parameter of type array like that:

```
  /pets/{id}:
    get:
      parameters:
      - name: id
        in: path
        description: ID of pet to use
        required: true
        type: array
        items:
          type: string
        collectionFormat: csv
```

To support this kind of parameters, we need to provide an instance of ```PathBindable```

Here is an example of how it is done for String in Play's code base:

```
  class Parsing[A](parse: String => A, serialize: A => String, error: (String, Exception) => String)(implicit codec: Codec)
      extends PathBindable[A] {

    def bind(key: String, value: String): Either[String, A] = {
      try {
        Right(parse(value))
      } catch {
        case e: Exception => Left(error(key, e))
      }
    }
    def unbind(key: String, value: A): String = serialize(value)
  }

  /**
   * Path binder for String.
   */
  implicit object bindableString extends Parsing[String](
    (s: String) => s, (s: String) => s, (key: String, e: Exception) => "Cannot parse parameter %s as String: %s".format(key, e.getMessage)
  )
```
